##################################
# Server
##################################
server.port=8082
spring.application.name=inventory-service


##################################
# Kafka Configuration
##################################

spring.kafka.bootstrap-servers=localhost:9092

# ---------- Consumer ----------
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# ? Correct deserialization setup
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.achal.events.OrderCreatedEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.trusted.packages=com.achal.order.model

# ---------- Producer ----------
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.admin.auto-create=false



##################################
# MongoDB Configuration
##################################
spring.data.mongodb.uri=mongodb://localhost:27017/inventorydb


##################################
# Logging (Helpful for debugging)
##################################
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=INFO


##################################
# Actuator (Optional but good)
##################################
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

