spring.data.mongodb.uri=mongodb://localhost:27017/orderdb
# Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Producer serializers
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Custom app properties (your class)
app.kafka.topicName=order-created-topic
#app.kafka.topicName=test